import Head from "next/head";
import Link from "next/link";
import { format, parseISO } from "date-fns";
import { getAllPosts } from "../lib/data";

export default function Home({ posts }) {
    return (
        <div className="h-screen">
            <Head>
                <title>albac: home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Projects</h1>
            </main>
            <div className="space-y-8 mt-4">
                {posts.map((item) => (
                    <BlogListItem key={item.slug} {...item} />
                ))}
            </div>
        </div>
    );
}

export async function getStaticProps() {
    const allPosts = getAllPosts();

    return {
        props: {
            posts: allPosts
                .slice(0)
                .reverse()
                .map(({ data, slug }) => ({
                    ...data,
                    date: data.date.toISOString(),
                    content: data.summary,
                    slug,
                })),
        },
    };
}

function BlogListItem({ slug, title, date, content }) {
    return (
        <div className="border font-medium space-y-2 text-sm hover:border-slate-400 dark:bg-slate-800 dark:border-white/5 border-black-400 rounded p-4">
            <div className="font-bold">
                <Link href={`/blog/${slug}`}>{title}</Link>
            </div>
            <div className="text-xs text-gray-600 dark:text-gray-200">
                {format(parseISO(date), "MMMM do, uuu")}
            </div>
            <div>{content}</div>
        </div>
    );
}
